version: '3'

services:
 
  rabbit:
    image: rabbitmq:3-management
    networks: 
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  postgres:
    image: postgres
    networks: 
      - default
    environment:
      POSTGRES_PASSWORD: "Postgres2021!"
    ports:
      - "5432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    

  server:
    restart: always
    build: ./
    networks: 
      - default
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
      - postgres
      - consumer-1
    environment: 
      - POSTGRES_HOST=postgres
      - PGPORT=15432
      - POSTGRES_DATABASE=poc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2021!
      - NODE_ENV=production
      - PORT=5000
  
  front:
    restart: always
    build: ./front
    networks: 
      - default
    ports:
      - "3000:3000"
    depends_on:
      - server

  consumer-1:
    restart: always
    build: ./Consumer
    networks: 
      - default
    depends_on:
      - rabbit
    environment: 
      - POSTGRES_HOST=postgres
      - PGPORT=15432
      - POSTGRES_DATABASE=poc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2021!
      - NODE_ENV=production
      - CONSUMER_NAME=Consumer1
  
  consumer-2:
    restart: always
    build: ./Consumer
    networks: 
      - default
    depends_on:
      - rabbit
    environment: 
      - POSTGRES_HOST=postgres
      - PGPORT=15432
      - POSTGRES_DATABASE=poc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2021!
      - NODE_ENV=production
      - CONSUMER_NAME=Consumer2

  consumer-3:
    restart: always
    build: ./Consumer
    networks: 
      - default
    depends_on:
      - rabbit
    environment: 
      - POSTGRES_HOST=postgres
      - PGPORT=15432
      - POSTGRES_DATABASE=poc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2021!
      - NODE_ENV=production
      - CONSUMER_NAME=Consumer3

  
networks:
  default:
    driver: bridge